# .streamlit/secrets.toml

[snowflake]
user = "EAP_DEV_USER"
password = "CG_eap@sfdev1"
account = "LI12981.south-central-us.azure"
warehouse = "LOADTEST_3_WH"
database = "EAPPOC"
schema = "STREAMLIT"
