# .streamlit/secrets.toml

[snowflake]
user = "EAP_DEV_USER"
password = "CG_eap@sfdev1"
account = "https://app.snowflake.com/south-central-us.azure/LI12981/"
warehouse = "LOADTEST_3_WH"
database = "EAPPOC"
schema = "STREAMLIT"
